### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/DMF#5]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [a function like “AsyncIo”](https://github.com/Microsoft/DMF/blob/d80ef12181d613ae8bc4d4ea3a6293d57e160aaa/DmfSamples/kmdf_fx2_dmf/exe/testapp.c#L990 "Update candidate: AsyncIo()").

**Comment by samtertzakian** [comment]
Inside DMF and its Libraries we do not have unnecessary NULL pointer checks. You can see this throughout the code. Thus, I will resolve this issue. (The example cited in this issue in sample code that is unmodified from its source in MSDN. It is not part of DMF proper. We are not modifying the samples, by design, to show they work unmodified.)
