### ISSUE TITLE
Why is `EnableLookAside` a `ULONG` and not a `BOOLEAN`?

### ISSUE THREAD

**Issue by rahul-ramadas** [microsoft/DMF#98]
See: https://github.com/microsoft/DMF/blob/3a67cb056a42637ce98fc489e355efc0fc8beeba/Dmf/Framework/Modules.Core/Dmf_BufferPool.h#L108

It confused me that `EnableLookAside` is a `ULONG`. I thought it was meant to specify the count of something, but apparently not, looking at how it is used. Any reason why it is not a `BOOLEAN`?

Same goes for other config structs that use the same field, like:
https://github.com/microsoft/DMF/blob/3a67cb056a42637ce98fc489e355efc0fc8beeba/Dmf/Modules.Library/Dmf_ContinuousRequestTarget.h#L154

**Comment by samtertzakian** [comment]
Hi, Rahul,
Many times when using flags, it turns out we need more than two settings. To allow for that we have made many flag values ULONG to allow further expansion in the future. It allows us to add another mode such as "EnableLookAsideAsXxx" in the future for example. 
Let me know if you have any other questions.
